apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-get-task
  namespace: dev-todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-get-task
  template:
    metadata:
      labels:
        app: dev-get-task
    spec:
      containers:
      - name: dev-get-task
        image: akkc01/gettasksmicro:e899b4aea9fbf6a141844847ae55945deee8c3ed
        ports:
        - containerPort: 8000
        env:
        - name: CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: db-connection-secret
              key: CONNECTION_STRING

        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"