apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-add-task
  namespace: dev-todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-add-task
  template:
    metadata:
      labels:
        app: dev-add-task
    spec:
      containers:
      - name: dev-add-task
        image: akkc01/addtasksmicro:7befff9fb5e4b51d71d7edaf06fa06bff319d377
        ports:
        - containerPort: 8000
        env:
        - name: CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: db-connection-secret
              key: CONNECTION_STRING

        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"