apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoui-micro
  namespace: dev-todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todoui-micro
  template:
    metadata:
      labels:
        app: todoui-micro
    spec:
      containers:
      - name: todoui-micro
        image: akkc01/todouimicro:1324462b842d8d084f8c2476258ee2873d678dfe
        ports:
        - containerPort: 80

        envFrom:
        - configMapRef:
            name: frontend-config

        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"